name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build Library AAR and Demo
        run: ./gradlew build

      - name: Archive Libary Build
        uses: kittaakos/upload-artifact-as-is@v0
        with:
          path: ./library/build/outputs/aar/*.aar

      - name: Archive Demo Build
        uses: kittaakos/upload-artifact-as-is@v0
        with:
          path: ./app/outputs/apk/debug/*.apk
