name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v4.4.0
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Library AAR and Demo
        run: ./gradlew build

      - name: Archive Libary Build
        uses: kittaakos/upload-artifact-as-is@v0
        with:
          path: ./library/build/outputs/aar/*.aar

      - name: Archive Demo Build
        uses: kittaakos/upload-artifact-as-is@v0
        with:
          path: ./app/build/outputs/apk/debug/*.apk
