name: Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  pr_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Archive Debug Build
        uses: kittaakos/upload-artifact-as-is@v0
        with:
          path: ./**/*.apk
