name: RC

on:
  release:
    types: [ published ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v4.4.0
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Library AAR and Demo
        run: ./gradlew build

      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./library/build/outputs/aar/library-debug.aar
          asset_name: improv-sdk_debug.aar

      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./library/build/outputs/aar/library-release.aar
          asset_name: improv-sdk_release.aar

      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./app/build/outputs/apk/debug/app-debug.apk
          asset_name: demo.apk
